### ISSUE TITLE
UI update

### ISSUE THREAD

**Issue by awolfe76** [cfpb/grasshopper-ui#33]
Have been playing around with this new UI, not a huge difference at all but more in line with some other CPFB UI's. Didn't want to do a pull request yet without a little feedback.

Hover has some animation, so does a click, on both the panel and the markers.
You can preview here - http://awolfe76.github.io/grasshopper-ui/dist/

@benguhin @lesgou @debseidner @wpears and everyone else too of course.

**Comment by wpears** [comment]
:+1:

**Comment by netplusdesign** [comment]
Which UI's were you thinking about? None that I can think of have a map. You're in virgin territory. Seems like your closest cousin is eRegs no? Going to have to figure out a better button than 'Get Lat/Long!' Just a magnifying glass might work. 

http://www.consumerfinance.gov/eregulations/search/1026?q=mortgage&version=2014-21849

Just two cents from the bleacher seats. 💭

**Comment by lesgou** [comment]
I like it! :+1: 
Two questions:
1) What's the difference between the black circles, green circles, and orange circles?
2) This isn't UI, but I typed in Irvine, CA; Los Angeles, CA.  For the Los Angeles one, the dot appears in a location that makes sense.  But for Irvine, CA, it's kind of off to the side of Irvine.

**Comment by awolfe76** [comment]
The only difference is the circles is black is default, all the points have been marked.
Green is active, you've clicked it so its highlighted.
Orange is when you hover, show the point but don't go there yet.

That might not make sense when only one x/y is shown, seems to make more sense when > 1 is shown.

Other ideas?

**Comment by awolfe76** [comment]
Will be closed with #45
