### ISSUE TITLE
Display error message for bad address entry

### ISSUE THREAD

**Issue by debseidner** [cfpb/grasshopper-ui#35]
I want to receive an error message if I enter an incomplete or incorrect address so that I know if there is an issue with the address and that I know whether the point returned is for the full address that I am trying to search.

**Comment by awolfe76** [comment]
@jmarin @wpears @hkeeler 
What are the minimum requirements for the address in the API query?

**Comment by jmarin** [comment]
@awolfe76 Not much at this point, it takes a single string and tries to match the search against the backend. This basically means you can start to get a list of candidates with a very short string being passed in. I think this requirement will probably need an address parser, which is planned for a later milestone. I'd pass this one to M2 for now
