### ISSUE TITLE
Dynamic configuration for running nginx inside Docker

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper-ui#53]
Right now the API Proxy backend is hardcoded into the nginx.conf file. Investigate ways to make it configurable at runtime

**Comment by hkeeler** [comment]
I think [Automated Nginx Reverse Proxy for Docker](http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/) describes the problem pretty well.  His solution is to use the [nginx-proxy](https://github.com/jwilder/nginx-proxy) Docker image, which uses [docker-gen](https://github.com/jwilder/docker-gen) under the hood...both of which he wrote. :)  It looks straightforward, and seems to have some traction in the community.  Seems worth investigating further.

@jmarin, I think you had some alternatives as well?

**Comment by jmarin** [comment]
@hkeeler @awolfe76 Since this is not a production website that will be exposed to the public, but more a test app, I think the easiest path would be to serve the content with Node.js and call it a day. The node server would proxy requests to the underlying APIs by reading environment variables passed at runtime, as we do with other services. 
Thoughts?

**Comment by hkeeler** [comment]
Per today's standup, we decided to stick with Nginx for now, and just get CORS working for grasshopper API.  This work will be tracked under https://github.com/cfpb/grasshopper/issues/125.

**Comment by awolfe76** [comment]
:+1: Working toward that, leaving nginx.conf as is for now.

**Comment by awolfe76** [comment]
Closing. #76 didn't close this but we're in an ok place. Can re-open if needed.
