### ISSUE TITLE
API failing

### ISSUE THREAD

**Issue by awolfe76** [cfpb/grasshopper-ui#74]
The API call from the UI is failing with a `502 Bad Gateway`. Likely to do with the `nginx.conf`.

Creating this as a reminder to look into it.

**Comment by schbetsy** [comment]
When Wyatt and I were setting up the docker-compose setup for the hmda-platform, we found that visiting `<server>/api` would lead to a `TOO_MANY_REDIRECTS` error.

When (and if?) we incorporate the geocoder into the api, we'll need to keep in mind that the nginx conf will need to be tweaked here.

See https://github.com/cfpb/hmda-platform-ui/pull/171

**Comment by awolfe76** [comment]
Closed by #76
